# generated by datamodel-codegen:
#   filename:  person.json
#   timestamp: 2025-04-02T03:39:39+00:00

from __future__ import annotations

from typing import List

from pydantic import BaseModel


class Name(BaseModel):
    type: str
    required: bool
    style: str
    units: None
    description: str
    options: List
    alias: List
    example: str
    default: None


class Author(BaseModel):
    type: str
    required: bool
    style: str
    units: None
    description: str
    options: List
    alias: List
    example: str
    default: None


class Organization(BaseModel):
    type: str
    required: bool
    style: str
    units: None
    description: str
    options: List
    alias: List
    example: str
    default: None


class Email(BaseModel):
    type: str
    required: bool
    style: str
    units: None
    description: str
    options: List
    alias: List
    example: str
    default: None


class Url(BaseModel):
    type: str
    required: bool
    style: str
    units: None
    description: str
    options: List
    alias: List
    example: str
    default: None


class Comments(BaseModel):
    type: str
    required: bool
    style: str
    units: None
    description: str
    options: List
    alias: List
    example: str
    default: None


class Model(BaseModel):
    name: Name
    author: Author
    organization: Organization
    email: Email
    url: Url
    comments: Comments
