# generated by datamodel-codegen:
#   filename:  person_schema.json
#   timestamp: 2025-04-04T23:26:09+00:00

from __future__ import annotations
from typing import Annotated, Optional
from pydantic import BaseModel, Field


class Person(BaseModel):
    name: Annotated[
        str,
        Field(
            description="Persons name, should be full first and last name.",
            examples="person name",
            title="name",
            json_schema_extra={"units": "m"},
        ),
    ] = None
    author: Annotated[
        Optional[str],
        Field(
            description="Persons name, should be full first and last name.",
            examples="person name",
            title="author",
        ),
    ] = None
    organization: Annotated[
        Optional[str],
        Field(
            description="Organization full name",
            examples="mt gurus",
            title="organization",
        ),
    ] = None
    email: Annotated[
        Optional[str],
        Field(
            description="Email of the contact person",
            examples="mt.guru@em.org",
            title="email",
        ),
    ] = None
    url: Annotated[
        Optional[str],
        Field(description="URL of the contact person", examples="em.org", title="url"),
    ] = None
    comments: Annotated[
        Optional[str],
        Field(
            description="Any comments about the person",
            examples="expert digger",
            title="comments",
        ),
    ] = None
