# generated by datamodel-codegen:
#   filename:  person_schema.json
#   timestamp: 2025-04-07T23:23:09+00:00

from __future__ import annotations
from typing import Annotated
from pydantic import BaseModel, Field


class Person(BaseModel):
    name: Annotated[
        str,
        Field(
            description='Persons name, should be full first and last name.',
            examples='person name',
            title='name',
        ),
    ]
    author: Annotated[
        str | None,
        Field(
            description='Persons name, should be full first and last name.',
            examples='person name',
            title='author',
        ),
    ] = None
    organization: Annotated[
        str | None,
        Field(
            description='Organization full name',
            examples='mt gurus',
            title='organization',
        ),
    ] = None
    email: Annotated[
        str | None,
        Field(
            description='Email of the contact person',
            examples='mt.guru@em.org',
            title='email',
        ),
    ] = None
    url: Annotated[
        str | None,
        Field(description='URL of the contact person', examples='em.org', title='url'),
    ] = None
    comments: Annotated[
        str | None,
        Field(
            description='Any comments about the person',
            examples='expert digger',
            title='comments',
        ),
    ] = None
